class Commands:
    LEECH = "leech@torleechpro_bot"
    PURGE = "purge@torleechpro_bot"
    PAUSEALL = "pauseall@torleechpro_bot"
    RESUMEALL = "resumeall@torleechpro_bot"
    STATUS = "status@torleechpro_bot"
    SETTINGS = "settings@torleechpro_bot"
    EXEC = "exec@torleechpro_bot"
    UPLOAD = "upload@torleechpro_bot"
    YTDL = "ytdl@torleechpro_bot"
    PYTDL = "pytdl@torleechpro_bot"
    ABOUT = "about@torleechpro_bot"
    GETLOGS = "getlogs@torleechpro_bot"
    SERVER = "server@torleechpro_bot"
    USERSETTINGS = "usetting@torleechpro_bot"
